# Generated by Django 5.2.7 on 2026-09-14 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConceptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_id", models.UUIDField(db_index=True)),
                ("scope_id", models.UUIDField(unique=True)),
                ("version", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
