from pathlib import Path
import re,json
from urllib.parse import unquote
R=Path(__file__).resolve().parents[3]; P=R/'outputs/research-platform-design-20260907'; T=R/'outputs/architecture/architecture-ai4s-2026-09-09'; O=Path(__file__).parent
files=[P/'产品设计方案.md',P/'章节索引.md',*sorted((P/'modules').glob('*.md')),T/'技术方案.md',T/'README.md',T/'章节索引.md',T/'ARCHITECTURE-SPINE.md',T/'技术决策记录.md',T/'模块开发与故障定位.md',T/'验收目录.md',T/'验收与实施映射.md',T/'V0.12检索方案技术契约.md',*sorted((T/'modules').glob('*.md')),O/'修订落实记录.md']
out=O/'文档检查记录.json'; out.write_text('{}',encoding='utf-8')
errors=[]; links=0; anchors=0
for f in files:
 s=f.read_text(encoding='utf-8')
 ids=re.findall(r'<a id="([^"]+)"',s)
 if len(ids)!=len(set(ids)): errors.append(f'duplicate anchors: {f}')
 for target in re.findall(r'\]\(([^)]+)\)',s):
  target=unquote(target.strip('<>'))
  if re.match(r'(https?://|mailto:|app:)',target):continue
  path,_,anchor=target.partition('#'); path=re.sub(r':\d+$','',path)
  dest=(f.parent/path).resolve() if path else f
  links+=1
  if not dest.exists(): errors.append(f'{f.relative_to(R)} -> missing {target}');continue
  # Existing autogenerated heading anchors are kept; all new stable anchors are checked.
  if anchor and re.fullmatch(r'[a-z][a-z0-9-]+',anchor):
   anchors+=1
   if f'id="{anchor}"' not in dest.read_text(encoding='utf-8'): errors.append(f'{f.relative_to(R)} -> missing anchor {target}')
p11=next((P/'modules').glob('11-*.md')); m=T/'验收与实施映射.md'
for letter,n,f in [('S',55,p11),('T',59,m)]:
 ids=[int(x) for x in re.findall(r'^\| '+letter+r'(\d+) ',f.read_text(encoding='utf-8'),re.M)]
 if len(ids)!=n or set(ids)!=set(range(1,n+1)): errors.append(f'{letter} rows: {ids}')
cat=(T/'验收目录.md').read_text(encoding='utf-8')
for letter,n in [('S',55),('T',59)]:
 ids=re.findall(r'^\| '+letter+r'(\d+) \|',cat,re.M)
 if len(ids)!=n: errors.append(f'catalog {letter} count={len(ids)}')
report={'date':'2026-09-29','product_version':'V0.18','technical_version':'T1.8','documents_checked':len(files),'local_links_checked':links,'stable_anchors_checked':anchors,'product_scenarios':55,'technical_scenarios':59,'errors':errors,'status':'passed' if not errors else 'failed','scope':'Static documentation checks only; no software or live retrieval acceptance executed.'}
out.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(report,ensure_ascii=False,indent=2))
raise SystemExit(bool(errors))
