# Generated by Django 5.2.7 on 2026-09-17 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_id", models.UUIDField(default=uuid.uuid4)),
                ("project_id", models.UUIDField(db_index=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(default="draft", max_length=24)),
                ("applicability", models.CharField(default="current", max_length=32)),
                ("scope_id", models.UUIDField()),
                ("scope_version", models.PositiveIntegerField()),
                ("scope_fingerprint", models.CharField(max_length=64)),
                ("concept_id", models.UUIDField()),
                ("concept_version", models.PositiveIntegerField()),
                ("concept_fingerprint", models.CharField(max_length=64)),
                ("template_id", models.CharField(max_length=80)),
                ("template_version", models.PositiveIntegerField()),
                ("template_hash", models.CharField(max_length=64)),
                ("input_snapshot", models.JSONField()),
                ("content_fingerprint", models.CharField(max_length=64)),
                ("unresolved_items", models.JSONField(default=list)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("request_hash", models.CharField(max_length=64)),
                ("creation_response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_key", models.CharField(max_length=80)),
                ("facet_type", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=240)),
                ("source_spans", models.JSONField()),
                ("term_refs", models.JSONField()),
                ("relation_hypotheses", models.JSONField(default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retrieval.searchplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchPlanBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_key", models.CharField(max_length=80)),
                ("task_refs", models.JSONField()),
                ("prerequisites", models.JSONField(default=list)),
                ("activation_conditions", models.JSONField(default=list)),
                ("status", models.CharField(default="planned", max_length=24)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retrieval.searchplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchPlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_key", models.CharField(max_length=80)),
                ("purpose", models.CharField(max_length=240)),
                ("required_blocks", models.JSONField()),
                ("optional_variant_refs", models.JSONField(default=list)),
                ("logical_ast", models.JSONField()),
                ("filters", models.JSONField(default=dict)),
                ("exclusions", models.JSONField(default=list)),
                ("output_partition", models.CharField(max_length=40)),
                ("prerequisites", models.JSONField(default=list)),
                ("expansion_conditions", models.JSONField(default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="retrieval.searchplan",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="searchplan",
            constraint=models.UniqueConstraint(
                fields=("plan_id", "version"), name="search_plan_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchplan",
            constraint=models.UniqueConstraint(
                fields=("project_id", "created_by", "idempotency_key"),
                name="search_plan_request_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchblock",
            constraint=models.UniqueConstraint(
                fields=("plan", "block_key"), name="search_block_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchplanbatch",
            constraint=models.UniqueConstraint(
                fields=("plan", "batch_key"), name="search_batch_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchplantask",
            constraint=models.UniqueConstraint(
                fields=("plan", "task_key"), name="search_task_key"
            ),
        ),
    ]
