from typing import Protocol

class PlatformRulePort(Protocol):
    def current_rule(self, platform: str): ...
class FileStorePort(Protocol):
    def put_immutable(self, content: bytes, metadata: dict) -> str: ...
    def get_authorized(self, key: str, access_facts): ...
class ModelPort(Protocol):
    def invoke(self, request_id: str, payload: dict): ...
class RemoteJournalPort(Protocol):
    def append(self, envelope: dict) -> str: ...
