# Generated by Django 5.2.7 on 2026-09-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DependencyEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.UUIDField(db_index=True)),
                ("target_id", models.UUIDField(db_index=True)),
                ("target_kind", models.CharField(max_length=80)),
                ("applicability", models.CharField(default="current", max_length=32)),
                ("approval_content", models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="mutationrecord",
            name="project_idempotency_key",
        ),
        migrations.AddField(
            model_name="mutationrecord",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="mutationrecord",
            constraint=models.UniqueConstraint(
                fields=("project", "actor", "key"), name="project_actor_idempotency_key"
            ),
        ),
        migrations.AddField(
            model_name="dependencyedge",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependency_edges",
                to="projects.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="dependencyedge",
            constraint=models.UniqueConstraint(
                fields=("project", "source_id", "target_id"),
                name="dependency_edge_once",
            ),
        ),
    ]
