# Generated by Django 5.2.7 on 2026-09-23 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_backfill_m0"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="external_processing_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FeedbackObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("identity", models.CharField(max_length=64)),
                ("content", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "kind", "identity"),
                        name="project_feedback_identity_once",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SuggestionReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("scope_id", models.UUIDField()),
                ("revision", models.PositiveIntegerField()),
                ("status", models.CharField(default="pending", max_length=24)),
                ("inputs", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "fingerprint"),
                        name="project_suggestion_input_once",
                    )
                ],
            },
        ),
    ]
